#!/bin/bash

# Start JupyterLab from the pixi environment inside the container and avoid
# inheriting host Jupyter config/kernels from the user's home directory.
apptainer exec --fakeroot --writable-tmpfs ngs-summer-course.sif jupyter lab --port="'$UID'" --ip="'$(hostname)'" --allow-root --no-browser
