name: ngs-course
channels:
  - conda-forge
  - bioconda
  - r
  - anaconda
  - plotly
  - grst
dependencies:
  - jupyterlab
  - bcftools
  - samtools[version='1.6']
#  - r-base>=4.0.0
#  - r-ggplot2
#  - r-dplyr
#  - r-irkernel
  - certifi
  - ipykernel
  - ipywidgets
  - minimap2
  - pandas
#  - r-vcfr
  - vcftools
#  - r-tidyr
  - matplotlib-venn
#  - ghostscript
#  - gnuplot
  - bash_kernel
#  - r-data.table
#  - r-gridextra
#  - r-cowplot
  - numpy
  - matplotlib
  - bioconductor-deseq2
#  - gsl
  - scanpy
  - python-igraph
  - leidenalg
  - python-annoy
  - multicore-tsne
  - pytables
  - star==2.7.10a
  - scikit-allel
  - fastqc
  - multiqc
  - qualimap
  - minimap2
#  - r-formattable
#  - r-venndiagram
#  - r-pheatmap
#  - r-mixomics
  - gffread
  - cython
  - scikit-image
  - imageio
  - tifffile
  - charset-normalizer
  - colorama
  - idna
  - igv
  - pydeseq2
  - bbknn
  - scrublet
  - scvelo
  - pip
  - nbconvert-webpdf
  - jupyterlab-nbconvert-nocode
  - jupyter-resource-usage
  - jupyterlab-topbar-text
  - autopep8
  - isort
  - yapf
  - black
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyter_bokeh
  - jupyter-lsp
  - jupyter-lsp-r
  - jupyter-lsp-python
  - jupyter-lsp-latex
  - jupyter-lsp-python-plugins
  - anaconda-toolbox
