channels:
  - conda-forge
  - bioconda
  - r
  - anaconda
  - plotly
  - grst
dependencies:
  - bioconda::regenie
  - conda-forge::jupyterlab
  - conda-forge::gcc_linux-64
  - bioconda::bwa
  - bioconda::bcftools
  - bioconda::samtools[version='1.6']
  - conda-forge::ca-certificates
  - conda-forge::openssl
  - conda-forge::r-base>=4.0.0
  - conda-forge::r-ggplot2
  - conda-forge::r-dplyr
  - conda-forge::r-irkernel
  - conda-forge::certifi
  - conda-forge::ipykernel
  - conda-forge::ipywidgets
  - bioconda::minimap2
  - conda-forge::pandas
  - conda-forge::r-vcfr
  - bioconda::vcftools
  - conda-forge::cxx-compiler
  - conda-forge::r-tidyr
  - bioconda::bioconductor-snprelate
  - bioconda::psmc
  - conda-forge::ghostscript
  - conda-forge::gnuplot
  - conda-forge::bash_kernel
  - bioconda::plink
  - conda-forge::r-data.table
  - conda-forge::r-gridextra
  - conda-forge::r-cowplot
  - conda-forge::numpy
  - conda-forge::networkx
  - conda-forge::dash
  - conda-forge::dash-bootstrap-components
  - conda-forge::dash-core-components
  - conda-forge::dash-html-components
  - conda-forge::matplotlib
  - conda-forge::r-qqman
  - bioconda::gcta
  - bioconda::admixture
  - conda-forge::conda-pack
  - bioconda::bioconductor-deseq2
  - conda-forge::gsl
  - conda-forge::scanpy
  - conda-forge::python-igraph
  - conda-forge::leidenalg
  - conda-forge::python-annoy
  - conda-forge::multicore-tsne
  - conda-forge::pytables
  - conda-forge::plotly
  - conda-forge::nbformat
  - bioconda::star==2.7.10a
  - conda-forge::scikit-allel
  - bioconda::fastqc
  - bioconda::multiqc
  - bioconda::qualimap
  - bioconda::minimap2
  - conda-forge::r-formattable
  - conda-forge::r-venndiagram
  - conda-forge::r-pheatmap
  - conda-forge::r-mixomics
  - bioconda::gffread
  - conda-forge::cython
  - conda-forge::scikit-image
  - conda-forge::imageio
  - conda-forge::tifffile
  - conda-forge::charset-normalizer
  - conda-forge::colorama
  - conda-forge::idna
  - conda-forge::pycparser
  - conda-forge::pyopenssl
  - conda-forge::pip
  - igv
  - pip
  - pip:
      - scvelo==0.3.3
      - rpy2==3.5.13
      - pydeseq2
      - batchglm #==0.7.4
      - bbknn==1.5.1
      - robustbase==0.2.8
      - scrublet==0.2.3
      - sparse #==0.13.0
      - requests #==2.27.1
      - six #==1.16.0
      - tqdm #==4.64.0
      - urllib3 #==1.26.9
      - wheel #==0.37.1
      - nbconvert #### jupyter plugins
      - nteract_on_jupyter
      - jupyter-resource-usage
      - jupyterlab-topbar-text
      - autopep8
      - yapf
      - isort 
      - black
      - jupyterlab-code-formatter
      - jupyterlab-git
      - jupyterlab-lsp
      - jupyter_bokeh
